[package]
name = "chessica-protocol"
version = "1.1.0"
edition = "2021"
license = "MIT"

[lib]
path = "rust/lib.rs"
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] } 
uuid = { version = "1.17.0", features = ["v4", "serde"] }
