[package]
name = "chessica-protocol"
version = "1.0.0"
edition = "2021"
license = "MIT"

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] } 
